### ISSUE TITLE
Cannot find specified path

### ISSUE THREAD

**Issue by sunscreem** [kilroyweb/homeboy#11]
Hey,

Sorry to bug you. 

I'm getting an error I don't really understand. Everything is working apart from the first stage (of creating the folder and laravel app itself).

You'll see if I run the command manually its working just fine.

Have a perhaps screwed up something in my .env?

```
ROBWORK@ROBWORK-PC MINGW64 /c/www
$ homeboy
What is your project's name? (project-1499616338)
What composer project? (laravel/laravel)
What local directory will store your project? (/c/www/)
Database Name? (project-1499616338)
Development Domain? (project1499616338.app)
The following tasks will be executed:
- Run Command: cd /c/www/ && composer create-project laravel/laravel project-1499616338
- (C:\Windows\System32\drivers\etc\hosts) add line: 192.168.120.120 project1499616338.app
- (/Users/ROBWORK/.homestead/Homestead.yaml) map : project1499616338.app to /home/vagrant/Code/project-1499616338/pub
lic
- (/Users/ROBWORK/.homestead/Homestead.yaml) add to databases: project-1499616338
- Run Command: cd /Users/ROBWORK/Homestead && vagrant provision
Run tasks? (Y) y
Creating project...
The system cannot find the path specified.
Adding Domain to hosts file (project1499616338.app)...
Mapping project1499616338.app in "/Users/ROBWORK/.homestead/Homestead.yaml"...
Adding database (project-1499616338) to "/Users/ROBWORK/.homestead/Homestead.yaml"...
Provisioning Vagrant...
The system cannot find the path specified.
<success>Complete! Visit: http://project1499616338.app</success>
```

```
ROBWORK@ROBWORK-PC MINGW64 /c/www
$  cd /c/www/ && composer create-project laravel/laravel project-1499616338
Installing laravel/laravel (v5.4.23)
  - Installing laravel/laravel (v5.4.23): Loading from cache
Created project in project-1499616338
> php -r "file_exists('.env') || copy('.env.example', '.env');"
```

**Comment by kilroyweb** [comment]
strange. Is homeboy installed in the /c/www directory as well or is it aliased from elsewhere?

I'm not going to be available for the rest of the day but I can take a closer look tomorrow. I would assume there's something off in the .env file.

**Comment by sunscreem** [comment]
Ah - no - homeboy is my home directory:

```
alias homeboy='php ~/homeboy/homeboy $*';
```

No rush for a reply. I appreciate the time you've already put into this :)

**Comment by kilroyweb** [comment]
Ignore that close,

Unlikely, but is your home directory in a different drive as /c/? I had trouble with switching dirs which made me make that d drive example env

**Comment by sunscreem** [comment]
Same drive. I'm using the bash shell if that makes any odds

**Comment by kilroyweb** [comment]
Give it a try to setup your .env config with C:\... paths instead of /c/. I'm not sure if there would be a difference in the way it's executed but it's worth a shot

_Sent from my Samsung SAMSUNG-SM-G930A using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by kilroyweb** [comment]
Also for testing, you could try to run something like:

homeboy vagrant status

Which might be a quicker test than the host command  

(Added in a recent commit you may need to pull a new version)

**Comment by sunscreem** [comment]
Right - good news. 

I've almost got this 100% working with the following .env file (changing the `c:/` helped as you suggested):

```
DEFAULT_COMPOSER_PROJECT=laravel/laravel
USE_COMPOSER=true
DEFAULT_FOLDER_SUFFIX=/public
DEFAULT_DOMAIN_EXTENSION=.app
HOSTS_FILE_PATH=C:\Windows\System32\drivers\etc\hosts
HOMESTEAD_HOST_IP=192.168.120.120
HOMESTEAD_FILE_PATH=C:\Users\ROBWORK\.homestead\Homestead.yaml
HOMESTEAD_SITES_PATH=/home/vagrant/Code/
HOMESTEAD_BOX_PATH="C:\Users\ROBWORK\VirtualBox VMs\homestead-7"
LOCAL_SITES_PATH=C:\www\
```

The only issue is that last one - my HOMESTEAD_BOX_PATH.

I can't work out (after trying quite a bit) where `vagrant provision` is going to work.

`homestead provision` works fine from anywhere, but `vagrant provision` is insisting I provide a "box name".

Any help much appreciated :)

**Comment by kilroyweb** [comment]
Ah, maybe this is an issue with the documentation / var naming. 

HOMESTEAD_BOX_PATH should be the path where you would normally cd into when running vagrant commands, not where the actual virtual machine lives.

So in your case, HOMESTEAD_BOX_PATH would probably be C:\Users\ROBWORK\Homestead

I'm not 100% but give that a try

**Comment by sunscreem** [comment]
Hey, Finally got some time to play with this again.

All working now with the following .env:

```
DEFAULT_COMPOSER_PROJECT=laravel/laravel
USE_COMPOSER=true
DEFAULT_FOLDER_SUFFIX=/public
DEFAULT_DOMAIN_EXTENSION=.app
HOSTS_FILE_PATH=C:\Windows\System32\drivers\etc\hosts
HOMESTEAD_HOST_IP=192.168.120.120
HOMESTEAD_FILE_PATH=C:\Users\ROBWORK\.homestead\Homestead.yaml
HOMESTEAD_SITES_PATH=/home/vagrant/Code/
HOMESTEAD_BOX_PATH=C:\www\Homestead
LOCAL_SITES_PATH=C:\www\
```

Thank you for taking the time to make and support this.

**Comment by kilroyweb** [comment]
Good to hear!
