### ISSUE TITLE
Composer Install

### ISSUE THREAD

**Issue by rdehnhardt** [kilroyweb/homeboy#12]
Would be great if it were possible to perform the same installation as "laravel/installer" from global composer

**Comment by kilrizzy** [comment]
We actually do :) ! If you pull the most recent version of homeboy and make sure you have the following vars set in your .env file:

LOCAL_SITES_PATH=/Users/*USER*/Code/
USE_COMPOSER=true
DEFAULT_COMPOSER_PROJECT=laravel/laravel

Then, running homeboy will create the project
