### ISSUE TITLE
Global composer package

### ISSUE THREAD

**Issue by kilroyweb** [kilroyweb/homeboy#17]
Thanks for the update @Kehet this looks like it's close. 

I'm not too familiar with setting up global composer packages but running:

composer global require "kilroyweb/homeboy" dev-master 

installs but it seems the vendor/autoload.php is updated one level up in the composer/vendor directory rather than within the kilroyweb/homeboy/vendor directory, which gives us the error:

require(C:\Users\Jeff\AppData\Roaming\Composer\vendor\kilroyweb\homeboy/vendor/autoload.php): failed to open stream: No such file or directory in ...

Any idea of a way to detect the location of that autoload.php file if installed via global?

**Comment by Kehet** [comment]
Sorry, I didn't notice this would be issue .. something like 

```php
if(file_exists(__DIR__.'/vendor/autoload.php')){
    require __DIR__.'/vendor/autoload.php';
}else{
    require __DIR__.'/../../autoload.php';
}
```

would probably fix this. Do you want me to open new pull request?

I noticed [packagist](https://packagist.org/packages/kilroyweb/homeboy) doesn't know about newest release (1.0.8) yet, could you please also update it? I think only owner are able to do that

**Comment by kilroyweb** [comment]
Heh wow, so simple.  No worries I'll get that added in

Thought I setup auto-update in packagist, I'll take a peek at that

**Comment by kilroyweb** [comment]
Awesome 1.0.9 working globally on my macbook
