### ISSUE TITLE
Per site public folder [enhancement]

### ISSUE THREAD

**Issue by Eduruiz** [kilroyweb/homeboy#23]
I would love to see an option to define the "public" folder when I run `homeboy`, I have 4 kinds of projects and the 4 uses different public folders (pure html, codeigniter MVC, codeigniter HMVC and laravel), so choosing it "per site" would help a lot. or maybe a parameter to do so if my case is really not the majority.

btw, thanks for the stunning app. 😃

**Comment by kilrizzy** [comment]
Yeah I've run into a few cases where I needed to switch it as well. I'll see if I can get a fix in today

**Comment by kilrizzy** [comment]
All set, as of 1.1.2 homeboy will ask for the folder suffix if composer is not used / if composer is used but it's not a laravel project. 👍
