### ISSUE TITLE
Add command

### ISSUE THREAD

**Issue by Helg18** [kilroyweb/homeboy#24]
Please, add a new command to configure and use -> cd /home/user/Code && laravel new project
Actually homeboy uses -> cd /home/user/Code && composer create-project laravel/laravel project

**Comment by kilroyweb** [comment]
We're using the composer create-project command to optionally allow a different default project other than laravel to be installed, though I'm sure 99% of uses happen to be laravel.

We could probably impliment this by adding in a config setting (like USE_LARAVEL_INSTALLER=true). I know the laravel new command has some caching to make it a bit faster but is there anything else as far as functionality that it does as well?

**Comment by Helg18** [comment]
So far no, however, when I find some other detail that can be improved I'll tell you. Thank you very much for taking the time to answer.
